apiVersion: v1
kind: DeploymentConfig
metadata:
  name: jenkins-sample
spec:
  template:
    metadata:
      labels:
        name: jenkins-sample
    spec:
      containers:
      - name: jenkins-latest
#        image: jenkins:latest
        image: 172.30.71.238:5000/sample01/jenkins:latest
        ports:
        - containerPort: 3306
          protocol: TCP
#        env:
#        - name: MYSQL_ROOT_PASSWORD
#          value: example
#        - name: MYSQL_DATABASE
#          value: redmine
  replicas: 1
  selector:
    name: jenkins-sample
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - jenkins-sample-latest
      from:
        kind: ImageStreamTag
#        name: jenkins:latest
        name: 172.30.71.238:5000/sample01/jenkins:latest
        ports:
  - type: ConfigChange
