apiVersion: v1
kind: BuildConfig
metadata:
  name: jenkins
spec:
  output:
    to:
      kind: ImageStreamTag
      name: jenkins:latest
  source:
    git:
      uri: https://github.com/yuji-k64613/openshift_jenkins.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:latest
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
